server:
  port: 8082
  servlet:
    session:
      tracking-modes: cookie
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Alwjddlwh123!
    url: jdbc:mysql://project-db-stu.ddns.net:3307/gogum0203
    username: gogum0203
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   # 데이터베이스 종류
    hibernate:
      ddl-auto: update   # jpa로 entity 처음 생성시 테이블 없으면 create, 만든 다음엔 update로 변경해야함
    properties:
      hibernate:
        format_sql: true
      
    show-sql: true
  # viewresolver
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
      
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    # thymeleaf 캐싱 false 로 해서 html 파일에 영향 없게 하기
    
#logging:
#  level:
#    org:
#      springframework: "debug"
#      springframework.web: "debug"